### ISSUE TITLE
Track results via git

### ISSUE THREAD

**Issue by ammgws** [WnndGws/fif_brackets#2]
So I can live vicariously. Check in the results file to repo?

**Comment by WnndGws** [comment]
Seems like a good idea, but I havent quote wrapped head around how we will track results.

What I am thinking is something along the lines of:
`MATCHUP 1: West Ham United (1&0) vs Borussia Dortmund (2&2)`

But I am not sure about where to go from there

**Comment by ammgws** [comment]
Was hoping it was already outputting results for instant gra-gitification.
